version: '3.8'

services:
  node1:
    image: nginx:1.25.2-alpine
    container_name: pharmasys-node1 
    volumes:
      - "/home/henrique/loadbalaspharmasys/build:/usr/share/nginx/html" 
    ports:
      - "8081:80"
    networks:
      - mynetwork

  node2:
    image: nginx:1.25.2-alpine
    container_name: pharmasys-node2 
    volumes:
      - "/home/henrique/loadbalaspharmasys/build:/usr/share/nginx/html" 
    ports:
      - "8082:80"
    networks:
      - mynetwork

  node3:
    image: nginx:1.25.2-alpine
    container_name: pharmasys-node3  
    volumes:
      - "/home/henrique/loadbalaspharmasys/build:/usr/share/nginx/html" 
    ports:
      - "8083:80"
    networks:
      - mynetwork

  node4:
    image: nginx:1.25.2-alpine
    container_name: pharmasys-node4  
    volumes:
      - "/home/henrique/loadbalaspharmasys/build:/usr/share/nginx/html" 
    ports:
      - "8084:80"
    networks:
      - mynetwork

  node5:
    image: nginx:1.25.2-alpine
    container_name: pharmasys-node5  
    volumes:
      - "/home/henrique/loadbalaspharmasys/build:/usr/share/nginx/html" 
    ports:
      - "8085:80"
    networks:
      - mynetwork

  loadbalancer:
    image: nginx:1.25.2-alpine
    container_name: pharmasys-loadbalancer  
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge